<?php
use const IncomeSample\Subheading\KEY;
use function IncomeSample\Subheading\save;
use function IncomeSample\Subheading\render;
$GLOBALS['n']=0;
function check($condition,$label) { global $n; if(!$condition) {throw new RuntimeException('FAIL: '.$label);} echo 'PASS '.(++$n).' '.$label."\n"; }
wp_set_current_user(1);
$id=wp_insert_post(['post_type'=>'post','post_title'=>'Sample post','post_status'=>'publish','post_author'=>1]);
$nonce=wp_create_nonce('income_subheading_save');
$_POST=['income_subheading_nonce'=>$nonce,'income_subheading'=>wp_slash('A "quoted" subheading & details')];
save($id);
check(get_post_meta($id,KEY,true)==='A "quoted" subheading & details','native save preserves quotes and ampersands');
check(render($id)==='<p class="post-subheading">A &quot;quoted&quot; subheading &amp; details</p>','render escapes output');
$_POST=['income_subheading'=>'overwrite'];save($id);
check(get_post_meta($id,KEY,true)==='A "quoted" subheading & details','missing nonce cannot overwrite');
$_POST=['income_subheading_nonce'=>'wrong','income_subheading'=>'overwrite'];save($id);
check(get_post_meta($id,KEY,true)==='A "quoted" subheading & details','invalid nonce cannot overwrite');
$_POST=['income_subheading_nonce'=>$nonce];save($id);
check(get_post_meta($id,KEY,true)!=='','absent field preserves value');
$_POST=['income_subheading_nonce'=>$nonce,'income_subheading'=>['bad']];save($id);
check(get_post_meta($id,KEY,true)!=='','array field does not overwrite');
$_POST=['income_subheading_nonce'=>$nonce,'income_subheading'=>''];save($id);
check(!metadata_exists('post',$id,KEY),'explicit empty field clears metadata');
$_POST=['income_subheading_nonce'=>$nonce,'income_subheading'=>'<img src=x onerror=alert(1)>Plain <b>text</b>'];save($id);
check(get_post_meta($id,KEY,true)==='Plain text','HTML removed on save');
$subscriber=wp_create_user('test_sub_'.time(),wp_generate_password(),'sub'.time().'@example.invalid');
wp_set_current_user($subscriber);
$_POST=['income_subheading_nonce'=>wp_create_nonce('income_subheading_save'),'income_subheading'=>'hacked'];save($id);
check(get_post_meta($id,KEY,true)==='Plain text','subscriber cannot edit another post');
wp_set_current_user(0);
check(render($id)==='<p class="post-subheading">Plain text</p>','public published subheading visible to visitor');
wp_set_current_user(1);$_POST=[];
wp_update_post(['ID'=>$id,'post_status'=>'draft']);
wp_set_current_user(0);
check(render($id)==='','draft subheading hidden from visitor');
wp_set_current_user(1);
check(render($id)!=='','authorized editor can preview draft');
wp_update_post(['ID'=>$id,'post_status'=>'publish','post_password'=>'local-secret']);
check(render($id)==='','password protected post does not leak subheading');
wp_update_post(['ID'=>$id,'post_password'=>'']);
$GLOBALS['post']=get_post($id);
check(do_shortcode('[post_subheading]')==='<p class="post-subheading">Plain text</p>','shortcode uses current post');
$empty=wp_insert_post(['post_type'=>'post','post_title'=>'Empty','post_status'=>'publish']);
check(render($empty)==='','empty value emits no markup');
$page=wp_insert_post(['post_type'=>'page','post_title'=>'Page','post_status'=>'publish']);
$_POST=['income_subheading_nonce'=>$nonce,'income_subheading'=>'wrong type'];save($page);
check(!metadata_exists('post',$page,KEY),'page is not mutated');
$_POST=[];
// Exercise the actual WordPress REST controller, not just the plugin callback.
$request=new WP_REST_Request('POST','/wp/v2/posts/'.$id);
$request->set_param('meta',[KEY=>'REST <b>clean</b>']);
$response=rest_do_request($request);
check($response->get_status()===200 && get_post_meta($id,KEY,true)==='REST clean','authorized REST save sanitizes field');
wp_set_current_user($subscriber);
$request->set_param('meta',[KEY=>'forbidden']);
$response=rest_do_request($request);
check($response->get_status()===403 && get_post_meta($id,KEY,true)==='REST clean','subscriber REST mutation rejected');
wp_set_current_user(1);
ob_start();IncomeSample\Subheading\editor(get_post($id));$html=ob_get_clean();
check(str_contains($html,'income_subheading_nonce') && str_contains($html,'value="REST clean"'),'native editor contains nonce and saved field');
$_POST=[];
wp_delete_post($id,true);wp_delete_post($empty,true);wp_delete_post($page,true);
require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($subscriber);
echo $GLOBALS['n']." checks passed on WordPress ".get_bloginfo('version').', PHP '.PHP_VERSION."\n";
