export type Status = 'Ready' | 'In progress' | 'Done';
export type Task = {id:string;title:string;project:string;owner:string;due:string;status:Status;description:string;criteria:string[]};
export const initialTasks:Task[]=[
{id:'WK-104',title:'Review the mobile onboarding flow',project:'Atlas / Customer portal',owner:'Maya Chen',due:'Sep 11',status:'Ready',description:'Review the first-run experience on small screens before the next release.',criteria:['Every control has a descriptive label.','The layout fits a 375px-wide screen.','Keyboard focus remains visible.']},
{id:'WK-103',title:'Connect the order status view',project:'Atlas / Customer portal',owner:'Noah Reed',due:'Sep 11',status:'In progress',description:'Show the current order state and a helpful empty state for new customers.',criteria:['All supported statuses have readable labels.','Empty and unavailable states are distinct.','Repeated refreshes do not create orders.']},
{id:'WK-102',title:'Prepare the content handoff',project:'Forma / Website refresh',owner:'Elena Park',due:'Sep 12',status:'Ready',description:'Package approved page copy and document the remaining editorial decisions.',criteria:['Each page has an owner.','Open questions are collected in one place.','No placeholder claims appear in approved copy.']},
{id:'WK-101',title:'Check the dashboard empty states',project:'Atlas / Customer portal',owner:'Maya Chen',due:'Sep 12',status:'In progress',description:'Make the dashboard useful before a customer has created their first record.',criteria:['Zero is not mistaken for missing data.','The next step is available from the empty state.','Search can be cleared without reloading.']},
{id:'WK-100',title:'Publish the component guidelines',project:'Forma / Website refresh',owner:'Noah Reed',due:'Sep 10',status:'Done',description:'Document spacing, reusable components, and accessible interaction patterns.',criteria:['Examples include light and dark themes.','Focus and disabled states are covered.','The source examples compile.']},
{id:'WK-099',title:'Review the release checklist',project:'Atlas / Customer portal',owner:'Elena Park',due:'Sep 10',status:'Done',description:'Confirm the release notes and rollback instructions before the next handoff.',criteria:['Changes have clear acceptance criteria.','Rollback steps are documented.','Known limitations are recorded.']}
];
export function filterTasks(tasks:Task[],query:string,status:string){const q=query.trim().toLocaleLowerCase();return tasks.filter(t=>(status==='All'||t.status===status)&&[t.title,t.project,t.owner,t.id].some(value=>value.toLocaleLowerCase().includes(q)));}
